name: Sync Fork With Upstream

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          github_token: ${{ secrets.PAT_FOR_SYNC }}

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/AliceLinks/LuoFuShanWeChatAppBackend.git
          git fetch upstream

      - name: Reset to upstream/master
        run: |
          git reset --hard upstream/master

      - name: Use PAT for push
        run: |
          git remote set-url origin https://Picarran:${{ secrets.PAT_FOR_SYNC }}@github.com/Picarran/LuoFuShanWeChatAppBackend.git

      - name: Force push to origin
        run: |
          git push --force origin master
